/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.ControlAudio;
import controlador.Cronometro;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import controlador.Nivel;

/**
 *
 * @author jose_
 */
public class Dificultad extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     * @param nombre
     * @param lbl
     * @return 
     */
    
    Nivel nvl = null;
    ControlAudio audio = new ControlAudio();
    Cronometro cronometro;
    
    public final Icon getFoto(String nombre, JLabel lbl) {
        int ancho = lbl.getWidth();
        int alto = lbl.getHeight();
        Image img = new ImageIcon(getClass().getResource("/img/" + nombre + ".png")).getImage();
        ImageIcon aux = new ImageIcon(img);
        int altoOriginal = aux.getIconHeight();
        int anchoOriginal = aux.getIconWidth();
        ImageIcon img2 = new ImageIcon(img.getScaledInstance((anchoOriginal * alto) / altoOriginal, alto, Image.SCALE_SMOOTH));
        return img2;
    }
    
    public Dificultad(Nivel nvl) {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        lblVolver.setIcon(getFoto("arrowLeft", lblVolver));
        lblDificil.setIcon(getFoto("iconDificil", lblDificil));
        lblMedio.setIcon(getFoto("iconMedio", lblMedio));
        lblFacil.setIcon(getFoto("iconFacil", lblDificil));
        this.nvl = nvl;
        this.cronometro = Cronometro.getInstance();
        cronometro.setLblHours(hours);
        cronometro.setLblMinutes(minutes1);
        cronometro.setLblSeconds(seconds);
        cronometro.actualizarLabels();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();
        btnDficil = new javax.swing.JPanel();
        lblDificil = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnMedio = new javax.swing.JPanel();
        lblMedio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnFacil = new javax.swing.JPanel();
        lblFacil = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        seconds = new javax.swing.JLabel();
        minutes1 = new javax.swing.JLabel();
        hours = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 29, 59));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(216, 33, 72));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 950, 10));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(218, 219, 189));
        jLabel3.setText("Desarrollado por: José Alejandro Pérez Arenas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 940, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(218, 219, 189));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DIFICULTAD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
        });
        jPanel1.add(lblVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        btnDficil.setBackground(new java.awt.Color(110, 191, 139));
        btnDficil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDficilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDficilMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDficilMousePressed(evt);
            }
        });
        btnDficil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDificil.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblDificil.setForeground(new java.awt.Color(21, 29, 59));
        lblDificil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDficil.add(lblDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 160));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 29, 59));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DIFICIL");
        btnDficil.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 190, 60));

        jPanel1.add(btnDficil, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 190, 290));

        btnMedio.setBackground(new java.awt.Color(110, 191, 139));
        btnMedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMedioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMedioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMedioMousePressed(evt);
            }
        });
        btnMedio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMedio.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblMedio.setForeground(new java.awt.Color(21, 29, 59));
        lblMedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMedio.add(lblMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 160));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 29, 59));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MEDIO");
        btnMedio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 190, 60));

        jPanel1.add(btnMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 190, 290));

        btnFacil.setBackground(new java.awt.Color(110, 191, 139));
        btnFacil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFacilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFacilMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFacilMousePressed(evt);
            }
        });
        btnFacil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFacil.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblFacil.setForeground(new java.awt.Color(21, 29, 59));
        lblFacil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFacil.add(lblFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 160));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(21, 29, 59));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FÁCIL");
        btnFacil.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 190, 60));

        jPanel1.add(btnFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 190, 290));

        seconds.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        seconds.setForeground(new java.awt.Color(218, 219, 189));
        seconds.setText(":00");
        jPanel1.add(seconds, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, -1));

        minutes1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        minutes1.setForeground(new java.awt.Color(218, 219, 189));
        minutes1.setText(":00");
        jPanel1.add(minutes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        hours.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        hours.setForeground(new java.awt.Color(218, 219, 189));
        hours.setText("00");
        jPanel1.add(hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        Inicio frame2 = new Inicio();
        frame2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMouseClicked

    private void btnDficilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDficilMouseEntered
        btnDficil.setBackground(new Color(32,128,66));
        jLabel4.setForeground(new Color(218,219,189));
        audio.playSound("encima");
    }//GEN-LAST:event_btnDficilMouseEntered

    private void btnDficilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDficilMouseExited
        btnDficil.setBackground(new Color(110,191,139));
        jLabel4.setForeground(new Color(21,29,59));
    }//GEN-LAST:event_btnDficilMouseExited

    private void btnMedioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedioMouseEntered
        btnMedio.setBackground(new Color(32,128,66));
        jLabel5.setForeground(new Color(218,219,189));
        audio.playSound("encima");
    }//GEN-LAST:event_btnMedioMouseEntered

    private void btnMedioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedioMouseExited
        btnMedio.setBackground(new Color(110,191,139));
        jLabel5.setForeground(new Color(21,29,59));
    }//GEN-LAST:event_btnMedioMouseExited

    private void btnFacilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacilMouseEntered
        btnFacil.setBackground(new Color(32,128,66));
        jLabel6.setForeground(new Color(218,219,189));
        audio.playSound("encima");
    }//GEN-LAST:event_btnFacilMouseEntered

    private void btnFacilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacilMouseExited
        btnFacil.setBackground(new Color(110,191,139));
        jLabel6.setForeground(new Color(21,29,59));
    }//GEN-LAST:event_btnFacilMouseExited

    private void btnFacilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacilMousePressed
        MemoFacil juego = new MemoFacil(nvl,0);
        audio.playSound("click");
        juego.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFacilMousePressed

    private void btnMedioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedioMousePressed
        MemoMedio juego = new MemoMedio(nvl,1);
        audio.playSound("click");
        juego.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMedioMousePressed

    private void btnDficilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDficilMousePressed
        MemoDificil juego = new MemoDificil(nvl,2);
        audio.playSound("click");
        juego.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDficilMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dificultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dificultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dificultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dificultad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dificultad(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnDficil;
    private javax.swing.JPanel btnFacil;
    private javax.swing.JPanel btnMedio;
    private javax.swing.JLabel hours;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDificil;
    private javax.swing.JLabel lblFacil;
    private javax.swing.JLabel lblMedio;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JLabel minutes1;
    private javax.swing.JLabel seconds;
    // End of variables declaration//GEN-END:variables
}
