/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.ControlAudio;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author jose_
 */
public class Ganaste extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     * @param nombre
     * @param lbl
     * @return 
     */
    
    int score = 0;
    int total = 0;
    ControlAudio audio = new ControlAudio();
    
    public final Icon getFoto(String nombre, JLabel lbl) {
        int alto = lbl.getHeight();
        Image img = new ImageIcon(getClass().getResource("/img/" + nombre + ".png")).getImage();
        ImageIcon aux = new ImageIcon(img);
        int altoOriginal = aux.getIconHeight();
        int anchoOriginal = aux.getIconWidth();
        ImageIcon img2 = new ImageIcon(img.getScaledInstance((anchoOriginal * alto) / altoOriginal, alto, Image.SCALE_SMOOTH));
        return img2;
    }
    
    public void pintar(){
        int tercio = total/3;
        if (score < (tercio*2)){
            lblEstrella1.setIcon(getFoto("conEstrella", lblEstrella1));
            lblEstrella2.setIcon(getFoto("sinEstrella", lblEstrella2));
            lblEstrella3.setIcon(getFoto("sinEstrella", lblEstrella3));
        }
        else if (score < total){
            lblEstrella1.setIcon(getFoto("conEstrella", lblEstrella1));
            lblEstrella2.setIcon(getFoto("conEstrella", lblEstrella2));
            lblEstrella3.setIcon(getFoto("sinEstrella", lblEstrella3));
        }
        else{
            lblEstrella1.setIcon(getFoto("conEstrella", lblEstrella1));
            lblEstrella2.setIcon(getFoto("conEstrella", lblEstrella2));
            lblEstrella3.setIcon(getFoto("conEstrella", lblEstrella3));
        }
        lblScore.setText("" + score);
    }
    
    public Ganaste(int score, int total) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.score = score;
        this.total = total;
        audio.playSound("felicidades");
        lblVolver.setIcon(getFoto("arrowLeft",lblVolver));
        pintar();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblScore = new javax.swing.JLabel();
        lblEstrella3 = new javax.swing.JLabel();
        lblEstrella1 = new javax.swing.JLabel();
        lblEstrella2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(21, 29, 59));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(216, 33, 72));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 950, 10));

        lblScore.setFont(new java.awt.Font("Roboto Black", 1, 60)); // NOI18N
        lblScore.setForeground(new java.awt.Color(216, 33, 72));
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("0");
        jPanel1.add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 330, -1));
        jPanel1.add(lblEstrella3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 230, 210));
        jPanel1.add(lblEstrella1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 230, 210));
        jPanel1.add(lblEstrella2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 230, 210));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(218, 219, 189));
        jLabel3.setText("FELICIDADES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(218, 219, 189));
        jLabel4.setText("PUNTAJE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVolverMousePressed(evt);
            }
        });
        jPanel1.add(lblVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMousePressed
        Inicio frame2 = new Inicio();
        frame2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ganaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ganaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ganaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ganaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ganaste(0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEstrella1;
    private javax.swing.JLabel lblEstrella2;
    private javax.swing.JLabel lblEstrella3;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblVolver;
    // End of variables declaration//GEN-END:variables
}
